### ISSUE TITLE
Does phraseapp pull support annotations? (e.g. `<!--suppress ImpliedQuantity -->`)

### ISSUE THREAD

**Issue by rsaunders100** [phrase/phrase-android#12]
We want to add this annotation to a key to ignore it from our lint.yml

e.g.
```
<!--suppress PluralsCandidate -->
<string name="my_key">%1$d Cats</string>
```
If we add it manually `phraseapp pull` will overwrite it.  Is there a way to support annotations like this?

**Comment by theSoenke** [comment]
Hi @rsaunders100, currently we don't support this as we don't store the annotation in Phrase. Could you contact us via the chat on phrase.com or at https://phrase.com/contact to discuss the use case and possible solutions?

**Comment by theSoenke** [comment]
I will close this issue for now as it is not directly related to the Android SDK. Please feel free to reach out to us via the above channels in case you have not yet
