### ISSUE TITLE
translationsChanged's of onSuccess callback always false

### ISSUE THREAD

**Issue by hichamboushaba** [phrase/phrase-android#15]
Using version 2.0.1 of the library, we noticed that the variable `translationsChanged` of the callback's `onSuccess` method is always false.

the name of the variable hints that it should be true when we get a new translations.

And I would like to suggest also to improve the callback by including the version number of the downloaded translation, this would be helpful for us to track the usage of feature.

**Comment by theSoenke** [comment]
Thanks for reporting this. We are currently working on a fix which should be available soon

**Comment by hichamboushaba** [comment]
@theSoenke can I know why this ticket is closed? on the releases page I don't see any new release.

**Comment by theSoenke** [comment]
@hichamboushaba Github closed it automatically as it was referenced from an internal PR :) Sorry for the confusion. The release will most likely be published later today or tomorrow morning

**Comment by hichamboushaba** [comment]
OK, thanks for the clarification 🙏

**Comment by theSoenke** [comment]
Version 2.0.2 has now been released and `onSuccess` is now correctly returning true when translations have changed.

Regarding the version number could you maybe elaborate a little bit what exactly would you like to track here? We do already provide some statistics in the interface on Phrase and maybe we could improve the statistics there

**Comment by hichamboushaba** [comment]
Our goal is to be able to track how many users are using the latest version of the translation, we would like to have an event sent to our backend when a user gets a new translation, et we want this event to have a meta including the version of the downloaded translation.

**Comment by theSoenke** [comment]
Thanks for the feedback. I can't promise when we will add this to the SDK but I've added this to our internal OTA features request and will provide an update here when there is any news
