### ISSUE TITLE
Fetched translations doesn't resolve the escaped characters 

### ISSUE THREAD

**Issue by mozarty** [phrase/phrase-android#16]
@theSoenke Thanks for the 2.0.0 update, it seems like the HTML tags issue has been fixed 

we are now experiencing a different issue with escaped strings 

![image](https://user-images.githubusercontent.com/1047227/71719333-4d5c1b80-2e1e-11ea-9e7a-5aa726b21347.png)

**Comment by theSoenke** [comment]
@mozarty Could you update to the latest release 2.0.1? This issue has been resolved there

**Comment by mozarty** [comment]
Thanks, it works!

**Comment by mozarty** [comment]
@theSoenke the 2.0.1 fixed the issue, but the issue of converting placeholders from ios is back so now we can't use 2.0.1 

we had to disable the integration again

**Comment by theSoenke** [comment]
@mozarty I'm sorry for the inconvenience. This issue is not related to the SDK but the delivered translation files. This will be fixed very soon and keep you updated

**Comment by theSoenke** [comment]
This has now been resolved. All releases going forward will convert the placeholders. To make sure the placeholders are converted you can create a new release
