### ISSUE TITLE
Version Range of the distribution not respected

### ISSUE THREAD

**Issue by hichamboushaba** [phrase/phrase-android#17]
Hi, we are facing an issue with the integration, which has lead to some crashes in Production, we noticed that the Min Version field is not respected, and that distributions are available to older versions as well.
While investigating we noticed this:
1. having a release v25 available only to versions >= 4.31.0
![Screen Shot 2020-02-24 at 10 08 25 AM](https://user-images.githubusercontent.com/1657201/75140419-2b309c80-56ef-11ea-8ea6-8deafd385f36.png)
2. and the app version set to 4.30.0
3. The SDK calls the API using the URL: https://ota.phraseapp.com/{distributionId}/{secret}/en_US/xml?client=android&unique_identifier=ba100b94-1a88-468c-b433-95fdea7bbcb2&sdk_version=2.0.1&version=4.30.0

And despite having an older version, the SDK got a 200OK response, with the releaseVersion 25, below a screenshot of the debugging session parameters:
![Screen Shot 2020-02-24 at 10 11 24 AM](https://user-images.githubusercontent.com/1657201/75140956-3932ed00-56f0-11ea-8d00-6c753f629745.png)

This is urgent, as it's stopping us from using the SDK in production.

**Comment by theSoenke** [comment]
Hi @hichamboushaba, we are working on a server side fix right now. This should be resolved very soon. I'm sorry for the issues caused here. I will keep you in the loop as soon as the fix is live

**Comment by theSoenke** [comment]
We've just rolled out the change for the min version check. This is backwards compatible to all existing SDK versions which will now always receive the correct release based on the version constraints.

Thank you for providing those detailed information and sorry for the inconvenience caused here

**Comment by hichamboushaba** [comment]
That was fast, thanks for the reactivity 👍
