### ISSUE TITLE
Double quotes added to some strings

### ISSUE THREAD

**Issue by hichamboushaba** [phrase/phrase-android#18]
Hey, we noticed an issue with the SDK, some messages seems to be surrounded with double quotes on the app.
When investigating we found that all those messages have some trailing white spaces, when we pull those message through the cli, we noticed the double quotes, this doesn't cause any issue when we don't use the SDK, as Android ignores the quotes. 
But when these messages gets pulled through OTA, the quotes are displayed on the UI, and we confirmed this by putting a breakpoint in the method `CustomResources.getText(id)`

**Comment by theSoenke** [comment]
Hi @hichamboushaba, which version of the SDK are you using? This should have been fixed in 2.1.2. If that should not be the case could you send me an example translation where this is occurring?

**Comment by hichamboushaba** [comment]
We were using version 2.1.0, I just updated to version 2.1.2, and it fixed the issue, thanks.
