### ISSUE TITLE
Android OTA update problem

### ISSUE THREAD

**Issue by erdincozden** [phrase/phrase-android#19]
Hello,
We integrated it into our Android app but Over the Air (OTA) doesn't work.  I debug your code, download xml file and write to cache successfully.  However, the layout on the screen are not updated.
How we can solve this problem ?

**Comment by theSoenke** [comment]
Hi @erdincozden, could you contact us via https://phrase.com/contact or the embedded chat on Phrase? There we could have a closer look at this specific case with your Phrase account

**Comment by erdincozden** [comment]
Solved by support team

**Comment by tuinui** [comment]
@erdincozden you know how to fix this?
right now I got the same issue when switching device language to indonesian
