### ISSUE TITLE
Access to dynamic strings

### ISSUE THREAD

**Issue by angelolloqui** [phrase/phrase-android#23]
Thanks to OTA we can also do some dynamic mappings from keys not previously present in the build but that comes afterwards. For example, to map server error codes into proper user messages is very handy.

In iOS, when we do something like `NSLocalizedString("my_server_error_key","") ` we can get the message from OTA, even if it was not previously included in the build but added later. 

However, in Android, I see no way to access it. I see there is a `TranslationRepository` with a `getString()` that would make the trick, but that repo is a private property of `Phrase`. Could you expose a way to access it? maybe something like:

Phase.class
```

    @Nullable
    public static String getString(String key) {
        return translationRepository.getString(key);
    }

```

Is there any other way we can access the OTA keys dynamically (and not by a `R.string`)?

**Comment by theSoenke** [comment]
Hi @angelolloqui, you are right that this is currently not possible in the Android SDK. My only concern would be that there is no guarantee anymore that there are translations when using dynamic strings. Compared to using ids from the strings resources file where we always have the fallback in case the SDK has not finished fetching the translations yet.

Does it happen on a regular basis that you have dynamic strings added for example from a server you need translations for?

**Comment by angelolloqui** [comment]
Sorry @theSoenke I totally missed your comment!

> Does it happen on a regular basis that you have dynamic strings added for example from a server you need translations for?

Not that much but in several places. The most common case we find are A/B test experiments, since we have a base string for the general public, but then from the remote config we can configure some other string to be used instead. Then code tries to fetch that string dynamically and default to the general one (in the binary) if none.

**Comment by angelolloqui** [comment]
Hi @theSoenke , any news about this? I am now using reflection to get access to the internals of phrase and its repository to get this, but it is fragile. Any plan to add it soon? thanks!
