### ISSUE TITLE
Duplicate class a.a.a.a.a in Phrase SDK 3.0.0

### ISSUE THREAD

**Issue by Neristance** [phrase/phrase-android#24]
Hey there,

I'm reaching out to you because it turned out that the new SDK version 3.0.0 delivers internally some obfuscated classes which are not in the `com.phrase.android.sdk `package. While compiling with another SDK we use (IDNow) we get a duplicate class error. 
I think for a public SDK that should not be done in this way, we will also report the same Issue to IDNow since it is not a very good style of designing an SDK. 

I hope you can help and please don't get me wrong obfuscation is totally fine :) But there should be a common package for those classes too.

Thanks for the help if you need further information please let me know.

Also here the compile error: 
`Duplicate class a.a.a.a.a found in modules jetified-android-sdk-3.0.0-runtime (com.github.phrase:android-sdk:3.0.0) and jetified-idnow-platform-3.20.1-runtime (de.idnow.android.sdk:idnow-platform:3.20.1)`

Cheers

**Comment by theSoenke** [comment]
Hey @Neristance, thanks a lot for reporting this. We just released another version 3.0.1. It should now keep the package name and fix the compile error

**Comment by Neristance** [comment]
@theSoenke Many thanks it does work!
