### ISSUE TITLE
PhraseContextWrapper does not cover application.getString()

### ISSUE THREAD

**Issue by Krillsson** [phrase/phrase-android#26]
In some cases, we fetch strings using application context. But it even though we've overriden `attachBaseContext` method in our application It seems like it is not possible to reach your custom resources.

In #25 you mentioned that you will remove this path from the integration. And I see you have already removed it from your documentation.

Our team would appreciate it if you were able to find another way of exposing your `PhraseResources` layer so we can still enable our usecase. Be it with via the singleton or somehow through the application context.

We were able to work around the issue by providing `Phrase.wrapApplicationContext(application)` directly to the modules that require it. But this is of course unintended usage of the API and not ideal.

**Comment by theSoenke** [comment]
Hey @Krillsson, we have released a fix the issue with `Phrase.wrapApplicationContext` with version 3.0.2. 

And I completely agree that it would be good to have an easier solution to access the translations from anywhere. This is something we are currently considering to add.

**Comment by Krillsson** [comment]
Can confirm, 3.0.2 fixed our problems. Thanks @theSoenke! 🙌
