### ISSUE TITLE
Special characters missing through OTA

### ISSUE THREAD

**Issue by Neristance** [phrase/phrase-android#27]
Hey @theSoenke ,
While using the SDK version 3.x we saw that we miss some special characters for example the `&`.

We have several keys in Phrase that are for example look like this `Test & other test`. If we do receive those strings via OTA it gets broken with the new SDK and the retrieved string does not contain the `& `anymore. 
I was tracing it in Charles Proxy and it seems that the Phrase server responds correctly `Test &amp; other test` I could also verify this by downgrading again to 2.1.3 of the SDK and all worked fine again.

Could you please verify this on your side as well and provide some fix.

Once again the steps to reproduce it:

1. Have a string with a special character e.g. `&` in Phrase
2. Get an OTA update via SDK 3.x
3. Retrieve the String in code (e.g. `context.getString()` ) and verify that the `&` is missing

Just to mention I was also trying the latest SDK 3.0.3 and it also had the issue

Thank you!

**Comment by theSoenke** [comment]
Hey @Neristance, thanks for reporting it. We're looking into this behavior and I'll keep you updated here when I have any news.

**Comment by DamienLevel** [comment]
Same issue here with "\" character (it's painful for unicode characters).

Thank you for a solution :)

**Comment by Kiruel** [comment]
Hi @Neristance just to know if you have any news about this bug ?
We are block on production because of this, so we will need to disable the SDKs for our next release.

**Comment by Neristance** [comment]
@Kiruel We are also just users of the SDK :) We have been downgrading to the last major version of 2.x which works for us.

**Comment by Kiruel** [comment]
Sorry tag the wrong guy :P ! @theSoenke ;) better.

**Comment by theSoenke** [comment]
Hey, the issue should now be resolved in version 3.0.4 https://github.com/phrase/phrase-android/releases/tag/3.0.4
