### ISSUE TITLE
Html stripped when using OTA in 3.x versions

### ISSUE THREAD

**Issue by angelolloqui** [phrase/phrase-android#33]
We have several texts using html to be able to add bold and some other minor style changes into a styled text.

We were able to use them with no problems up until we upgraded phraseapp sdk from 2.1.3 to 3.0.5 (we are not using 3.0.6 due to some androidx incompatibility in the bottom navigation that we need to solve first). However, with the newer version, every time we try to get the string it returns it without any HTML tag. So:

This code:
```
getString(R.string.social_feed_post_match_user_title, name, tenant)
```

with this text value (in the local resources) :
```
    <string name="social_feed_post_match_user_title"><![CDATA[<b>%1$s</b> shared a result in <b>%2$s</b>]]</string>
```

Returns:

```
{name} shared a result in {tenant}
```

If we disable OTA altogether (removing the delegate, the application context wrapper and the `Phrase.setup`) then the code returns the expected string:
```
<b>{name}</b> shared a result in <b>{tenant}</b>
```

This feature is crucial for us, and a blocker to update the library

**Comment by angelolloqui** [comment]
A little piece of extra info. It seems the bug is reproducible in 2.3.1 too, but maybe just in some devices. In particular I have managed to reproduce it in a Samsung Galaxy J7 with Android 8.1.0 and in an emulator with Android 11.

**Comment by angelolloqui** [comment]
Hi @theSoenke can you help us out here? thanks!

**Comment by theSoenke** [comment]
Hi @angelolloqui, I'm sorry for my delayed response. We're looking into this behavior now and I hope to provide an update early next week

**Comment by angelolloqui** [comment]
Hello @theSoenke ... not sure if you have any news here... thanks!

**Comment by DarkMinstrel** [comment]
Hi @angelolloqui !
There are no html tags because you're using the `getString()` method. 
As per documentation, `getString()` strips all styling information and returns the naked string.
If you want to get styled `CharSequence`, try using `getText()` instead.

Alternatively, if you need to combine placeholders and styles in the same string, you should HTML-escape it, replace placeholders, and finally convert it with `Html.fromHtml()`. Please see the official Android docs on this topic:
https://developer.android.com/guide/topics/resources/string-resource.html#StylingWithHTML

**Comment by angelolloqui** [comment]
Hi @DarkMinstrel , thanks for answering but I probably did not explain myself correctly. 

We do use `Html.fromHtml()` from the string to set it as HTML, that is not the problem. 
The strings do not need to be escaped unless there is a conflict on the HTML itself with your xml, in which case you could use the CDATA tag, check the example you provided, how the example string looks like:

```    
<string name="welcome">Welcome to <b>Android</b>!</string>
```

By the way, this all works perfectly when we do `phrase pull`. For example, this string gets escaped  automatically by the running the command:

```
    <string name="auth_home_terms_and_conditions"><![CDATA[By registering you are accepting our <br><a href=\"%1$s\">terms of use</a> and <a href=\"%2$s\">privacy policies</a>]]></string>
```

**Everything works as expected**, and we follow Android guidelines, **until OTA comes into play**. From that moment the HTML is stripped out.

The usage of `getText()` is not a valid alternative since it requires implementation changes all around the app. This is clearly a bug in the OTA management.

**Comment by angelolloqui** [comment]
By the way, I see you are quite busy, because you took 21 days to answer a "is your fault", probably not dedicating 5min to check your code first. Can you at least provide access to the source code so I could fork it, fix it and provide a PR? I can understand you have no resources to check this now but for us this is a very important bug that needs fix or we will stop using Phrase and look for an alternative. These kind of libraries should be open to anyone, the strength of your product is the whole platform, the code in the sdk has little value without any of it.

**Comment by DarkMinstrel** [comment]
In order to preserve CDATA when using Phrase, you need to enable this checkbox in your distribution settings:
![image](https://user-images.githubusercontent.com/12033349/133594627-32424756-a870-4a70-953b-9ea8a283e31f.png)

**Comment by angelolloqui** [comment]
That sounds like it but I can not find that option. Where is that checkbox located? I have this when creating an new OTA release:

<img width="644" alt="Screenshot 2021-09-16 at 14 17 28" src="https://user-images.githubusercontent.com/1382659/133610775-313c6ddf-3bb6-439b-89d0-976444d6a1a0.png">

**Comment by angelolloqui** [comment]
Got it, let me try that... 🤞

**Comment by angelolloqui** [comment]
Awesome!! thanks @DarkMinstrel !! that seemed to work perfectly!! I am closing the issue and keep this change under test. If I see any other side effect from activating this checkbox I will let you know by reopening!
