### ISSUE TITLE
Translations update always triggers onFailure callback

### ISSUE THREAD

**Issue by Alpexs** [phrase/phrase-android#34]
Hello,

After updating Phrase OTA SDK from 2.x to 3.0.x we noticed an issue during translations update which always fails. Looking at stack trace in debugger I noticed an _XmlPullParserException_ , I don't know how to get more informations about that exception, I checked the translation files for maybe some weird characters and tried to remove it on a new OTA release, nothing changed

On 2.x version updates were working fine but we were having issues with realtime updates, that's why we decided to try version 3.X

![Screenshot 2021-10-12 at 13 40 21](https://user-images.githubusercontent.com/36225951/136949442-68433b12-aa33-4376-8531-1f6863fedcd7.png)

```
Error(e=org.xmlpull.v1.XmlPullParserException: unexpected type (position:TEXT 
     delete use...@130:5 in java.io.InputStreamReader@a03213b) )
```

I've read that appcompat may have impact on library proper working, we were using 1.2.0, tried to bump until 1.3.1, same behaviour

Other gradle settings

```
    compileSdkVersion 30
...
    buildToolsVersion '30.0.3'        
    minSdkVersion 24
    targetSdkVersion 30
..
    compileOptions
    {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
```

Let me know if you need more information ! Thanks.

**Comment by theSoenke** [comment]
Hey @Alpexs, could you contact us via https://phrase.com/contact or the embedded chat in Phrase? And please include the distribution id and environment. That would really help us to debug this. Thanks!

**Comment by mr-coin-coin** [comment]
Thanks @Alpexs , I had the same issue with SDK v3.0.6, but not anymore after downgrading to 2.1.3 or either 3.0.0

**Comment by theSoenke** [comment]
Could you check whether any of your keys in Phrase contains a description with `-->`? This can cause issues with the parser as it is incorrectly closing the comment: `<!-- lorem --> ipsum -->`. We're also looking into escaping these characters to address this

**Comment by mr-coin-coin** [comment]
I don't think this is related as my solution couldn't have compiled.
But just in case, I have looked for it and it returned no result.
The only similar string that I have is a series of dashes  "------------------------------"

**Comment by theSoenke** [comment]
Closing it for now. Feel free to reopen when still an issue
