### ISSUE TITLE
OTA update strings should fallback to local string resources

### ISSUE THREAD

**Issue by D-Fox** [phrase/phrase-android#35]
Phrase version: 3.0.6

Steps to reproduce:
- The application contains local string resources `A`, `B`, `C` and `D`
- OTA update contains string resources `A`, `B`, `C` but not `D`
- When `D` string resource is queried (using `context.getString`) empty string is returned

Expected behavior
- String resources that are not present in OTA update should return local string resource

**Comment by LethalMaus** [comment]
I noticed this issue as well

**Comment by timpauls1991** [comment]
I can confirm a similar issue exists:

Phrase SDK 3.1.3
App contains `en` and `de` strings. OTA distribution release contains only `en`. When settings the locale code in the app to `de-DE`, Phrase returns the default strings (`en`) instead of the bundled `de` strings as a fallback.

**Comment by theSoenke** [comment]
Hi @timpauls, could you check the fallback distribution settings? When the option` Fallback languages uses the default locale` is enabled it will fall back to the default locale, which might be `en` in your case

<img width="746" alt="Screenshot 2023-11-03 at 11 36 42" src="https://github.com/phrase/phrase-android/assets/1757301/9a763fef-fb95-46ac-9d8e-d770de9d2fdc">

**Comment by timpauls** [comment]
Hi @theSoenke, it doesn't really seem like this works as you suggest.

Disclaimer: I haven't been actively using this feature in over a year, and only played around with it a little bit right now. I pulled in the latest SDK version but did not change any of the integration code.

I would say what I saw was unexpected behavior.
Firstly, it's not clear if changing this distribution setting changes anything directly or if it requires a new release within the distribution. I changed the distribution settings as per your screenshot and then created new releases, just to be safe. What I did was:

- have an app with bundled en + de strings
- create a release with en + de strings
- create a release with just en strings
- launch app with en locale: works (OTA strings)
- launch app with de locale: works (OTA strings)
- remove release with en + de strings
- launch app with de locale. Expectation: app displays bundled de strings, actual result: app displays **bundled en** strings (so not even the OTA en strings).
- launch app with en locale: works (displays OTA en strings)

Same, if there was never a release containing de strings in the first place.

en is indeed the default locale. But that should not have been used here, I guess.

**Comment by theSoenke** [comment]
Thanks for your feedback and detailed reproduction steps. In this case the expected behaviour should be that bundled de strings are displayed. If no OTA translations are present translations should be same as without the SDK. I'm going to create a task to look deeper into this.

“Use language fallback” will only be applied for new releases as this changes the release content. Both other fallback options will be applied immediately (or at most a few seconds delay).

**Comment by theSoenke** [comment]
Hi @timpauls, the latest version 3.9.0 includes a bugfix for the fallback to bundled translations https://github.com/phrase/phrase-android/releases/tag/3.9.0 Hopefully this should resolve the issue then

**Comment by docstun** [comment]
Closed since we believe this is fixed, please feel free to comment if it should turn out to not be resolved for you 👍
