### ISSUE TITLE
Dark Mode Problem With MODE_NIGHT_FOLLOW_SYSTEM Selected

### ISSUE THREAD

**Issue by prisyazhnuy** [phrase/phrase-android#36]
There is an error on the library where if user want to use Dark Mode with flag MODE_NIGHT_FOLLOW_SYSTEM.

MODE_NIGHT_NO, MODE_NIGHT_YES or MODE_NIGHT_AUTO_BATTERY works fine and only problem occurs due to the selection of MODE_NIGHT_FOLLOW_SYSTEM.

Once system dark mode is changed, the application did not restarted with proper dark mode theme in MODE_NIGHT_FOLLOW_SYSTEM selected.

The problem caused due to the Application class method overriding.

Causes Error:

 override fun attachBaseContext(newBase: Context?) {
        super.attachBaseContext(Phrase.wrapApplicationContext(newBase ?: this))
    }

**Comment by subspider** [comment]
should it be ?

```
if (newBase != null) {
            super.attachBaseContext(Phrase.wrapApplicationContext(newBase))
        } else {
            super.attachBaseContext(null)
        }
```

**Comment by theSoenke** [comment]
Hi, in version 3.3.1 a fix for the internal resource handling was implemented, which might affect this issue. Could you try whether it resolves it for you?

**Comment by docstun** [comment]
Closing this for now since we believe the issue should be resolved. Feel free to comment in case it still occurs!
