### ISSUE TITLE
OTA support multiple environment

### ISSUE THREAD

**Issue by cchaouachi** [phrase/phrase-android#39]
can OTA support multiple environment?

**Comment by theSoenke** [comment]
Hey @cchaouachi, could you describe a bit what would be an environment for you? For example there is a preview and production environment for every release. In addition you could create as many distributions as you like and each could represent a different environment with another release cycle

**Comment by cchaouachi** [comment]
Hey @theSoenke
Sorry , I mean project 
In fact we are using multiple project in our app, with different phrase project. 
is it possible to use OTA in this case with different project in the same application?

**Comment by theSoenke** [comment]
Hey, thanks for clarifying. Unfortunaltey the SDK only supports one Phrase project at a time. Adding more projects would mean multiple requests and currently it's restricted to a single project per app

**Comment by cchaouachi** [comment]
@theSoenke Thank you for quick your response !
