### ISSUE TITLE
Missing support for ComponentActivity

### ISSUE THREAD

**Issue by tajchert** [phrase/phrase-android#40]
In Compose-only apps there is no need for `AppCompatActivity` and it would be very good to support usage in `ComponentActivity` without need to add AppCompat dependency

**Comment by theSoenke** [comment]
Hey @tajchert, that's a good point. Let me check whether there is a good solution to this already or if it would require some changes in the SDK

**Comment by RobinCosmo** [comment]
Any update on this?

**Comment by theSoenke** [comment]
Hi @RobinCosmo, unfortunately this has got a delayed due some other priorities. But I would also like to get this resolved soon and reprioritized this again. I hope I can provide another more concrete update soon

**Comment by theSoenke** [comment]
Hi, Jetpack compose is now supported by the SDK. To enable compose support you'll need to import the compose package `implementation "com.phrase.android:ota-sdk-compose:3.5.0"` and wrap the Jetpack Compose code in `Phrase { ... }`
