### ISSUE TITLE
Compatibility with Android 6 and 7

### ISSUE THREAD

**Issue by emiltsang86** [phrase/phrase-android#43]
I am using Phrase OTA version `3.1.3`.

I have tried to launch the app in `Android Emulator` with `Android 6 & 7`.
I found the `TextView` keeps displaying the `old` translations,
**NOT** the translation updated with `OTA`.

Is the Phrase OTA 3.1.X compatible with `Android 6 & 7`?

**Comment by theSoenke** [comment]
Hi, Android 6 and 7 should be supported and is also something we test at a minimum for Android 7. Could you maybe reach out to us via https://phrase.com/contact or the chat on Phrase to take a look at your specific project setup what might be the reason translations do not show up?

**Comment by theSoenke** [comment]
Hi @emiltsang86, were you able to solve this? Both Android versions should be supported by the SDK and if translations are not displayed something else might cause it. I'll close this issue for now but let me know or reach out to our support at https://phrase.com/contact  if there are still some issues
