### ISSUE TITLE
CLI - Ability to specify `tools:locale`

### ISSUE THREAD

**Issue by D-Fox** [phrase/phrase-android#46]
In order to make Lint checks work properly for default (without language folder suffix) resource xml, `tools:locale` must be defined in resources xml tag:

`<resources xmlns:tools="http://schemas.android.com/tools" tools:locale="cs">`

It would be nice to be able to specify this this through `.phrase.yml` or CLI argument.

**Comment by forelabs** [comment]
Thank you for the suggestion and sorry for the really late reply. We will consider to add a format option for android xml files to include the `tools` definition according to the documentation: https://developer.android.com/studio/write/tool-attributes#toolslocale

**Comment by jablan** [comment]
@D-Fox hi, we have added this feature as a default, so all Android XML format exports now have this attribute.

**Comment by forelabs** [comment]
@D-Fox We received customer feedback that including this by default is causing errors. We will most likely adjust the change back to not include it by default but introduce a format option you can specify as you requested initially. I am sorry for any invonveniance.

**Comment by forelabs** [comment]
@D-Fox We introduced the change to add this information only when a specific format option is given.
It is called `include_tools_locale_definition`

The documentation of this new format option parameter and the selection in the UI do follow asap, but you can already make use of it within your cli / .phrase.yml file.
