### ISSUE TITLE
[Android] Some strings still stay its old language after calling Phrase.setLocaleCode(localeCode)

### ISSUE THREAD

**Issue by Jasminelau07** [phrase/phrase-android#47]
Phrase version 3.0.6
Using Kotlin and RIBs to build the app
After changing language using Phrase.setLocaleCode(localeCode) and Phrase.updateTranslations(), some string didn't update their language into the new one.
For those un-updated strings were declared by the xml `andreoid:text` attribution but it can be updated once set the text programmatically.
Can anyone help?
Thank you very much.

**Comment by theSoenke** [comment]
Hi @Jasminelau07, after changing the locale code is the activity being refreshed to make sure translations from the new locale are displayed? Also as a note  `Phrase.updateTranslations()` is updating the translation in a background thread. To react to a completed translation update you could provide a callback and refresh the screen right after 
```
Phrase.updateTranslations(new TranslationsSyncCallback() {
    @Override
    public void onSuccess(boolean translationsChanged) {
    }

    @Override
    public void onFailure() {
    }
});
```

**Comment by theSoenke** [comment]
Hi @Jasminelau07, is this still an issue with the latest SDK? If that's the case could you check that the latest translations have been fetched with `Phrase.getTranslations().getString("keyname")`?

**Comment by docstun** [comment]
We believe this should be resolved so I am closing this one. @Jasminelau07 please feel free to comment if you think this is still an issue, happy to reopen the issue then.
