### ISSUE TITLE
XmlPullParserException gets Logged by Phrase OTA

### ISSUE THREAD

**Issue by ignindra** [phrase/phrase-android#50]
Hi, I get this exception when I tried to use Phrase OTA in my new basic Android project using our existing distribution id & environment.
The sample app that I tried is basically a carbon copy of sdk sample usage [in here](https://github.com/phrase/android-sdk-example).

This is the only message/error that appeared on logcat.
```
D/Phrase OTA: org.xmlpull.v1.XmlPullParserException: expected: /b read: string (position:END_TAG </string>@264:77 in java.io.InputStreamReader@ed564b1).
```

The detail on translated text that I'm using is:
- translation key: `STRING_CLOSE`
- translation value: `Close`

More details:
- Phrase SDK version 3.1.6
- AppCompat 1.3.0
- minSdk 22
- targetSdk 32
- Currently we don't set the distribution version yet in Phrase web integration page. So I assume any version should get the text.
- I'd tried providing localecode as well in the code to no avail.

Kindly help explain what is going on here.

**Comment by ignindra** [comment]
Hi Erika, is there any update on the issue I faced here?

**Comment by theSoenke** [comment]
Hi @ignindra, could you share the distribution id with us at support@phrase.com or via the chat on phrase.com? Then we can take a closer look at this exact issue and it should help a lot to track down the cause

**Comment by ignindra** [comment]
I managed to found the fix by toggled off the "Use language fallback" in the distribution configuration. I'm not sure why it affects the Android project but, it doesn't affect iOS.

For now I'll close this ticket.

Thank you.

**Comment by theSoenke** [comment]
@ignindra Glad to hear this is solved. Maybe if you have a moment I would still be really interested to look into this when you could share a distribution and release where this happened to investigate and resolve the root cause
