### ISSUE TITLE
Migrate to a different host provider

### ISSUE THREAD

**Issue by mariodujic** [phrase/phrase-android#51]
Phrase is hosted on https://jitpack.io, and they had a lot of issues lately with keeping their services running. https://github.com/jitpack/jitpack.io/issues?q=is%3Aissue+broken. With Jitpack down, we're unable to create a build that depends on Phrase.

Can a Phrase SDK for Android get a different host provider?

**Comment by theSoenke** [comment]
Hi @mariodujic, we have noticed the same issues and are considering alternatives as well. Do you have maybe some good experiences with a hosting provider?

**Comment by mariodujic** [comment]
> Hi @mariodujic, we have noticed the same issues and are considering alternatives as well. Do you have maybe some good experiences with a hosting provider?

It might be a good long-term solution to publish it on `MavenCentral`.
