### ISSUE TITLE
Got Status 422 : parameter 'version' is not a valid semver version

### ISSUE THREAD

**Issue by isymphonyz** [phrase/phrase-android#52]
I found this error from this url : https://ota.phraseapp.com/07b000138453eb557719a90b4921499c/ZqIHaY2tJeuaMftKoIebva02Bk9E-Ld-_hxW_AlLYgU/en_US/xml?client=android&unique_identifier=2fecf1ba-b044-4f71-9e39-04fa172400d7&sdk_version=3.2.2&app_version=1.0

I think it because the value of app_version parameter is not valid. If I change it to app_version=1.0.0, it's worked.

Do you have any solution for me to fix it ?

**Comment by theSoenke** [comment]
Hi @isymphonyz, we're trying to automatically use the app version. If it is not in the semver format you could still use `Phrase.setAppVersion("1.0.0")` to set a semver release version. Hope this helps!

**Comment by isymphonyz** [comment]
It's worked. Thanks a lot.
