### ISSUE TITLE
Some locales not set properly by xml

### ISSUE THREAD

**Issue by tigran-mkhitaryan** [phrase/phrase-android#54]
Hello. We use "Over the air" integration in our app and we faced issue with applying strings in xml. We use in our xml file something like this.

```
 <com.google.android.material.tabs.TabLayout
                android:id="@+id/tabLayout"
                style="@style/TabLayoutWallet"
                android:layout_width="match_parent"
                android:layout_height="match_parent">

                <com.google.android.material.tabs.TabItem
                    android:layout_width="wrap_content"
                    android:layout_height="match_parent"
                    android:text="@string/text1" />

                <com.google.android.material.tabs.TabItem
                    android:layout_width="wrap_content"
                    android:layout_height="match_parent"
                    android:text="@string/text2" />

            </com.google.android.material.tabs.TabLayout>
```
Tab items not load locales and its show only value that stored locally in strings.xml only. Also we faced with this issue when we use **helperText** in **com.google.android.material.textfield.TextInputLayout** widget.  As a workaround we set a value of this type of views by code but it's so annoying. Please provide any help.

**Comment by theSoenke** [comment]
Hi @tigran-mkhitaryan, this should now be resolved in 3.4.0 https://github.com/phrase/phrase-android/releases/tag/3.4.0
