### ISSUE TITLE
Download all available translated texts

### ISSUE THREAD

**Issue by ma-unicsoft** [phrase/phrase-android#57]
We are using **Phrase Android SDK** in one of our important projects where translation delivery and updates are **crucial** for us.

On first ever launch we can see that even after calling `Phrase.setup(...)` and `Phrase.updateTranslations()` still we don't get all available translation cached in files. From logs we can understand that these files are not available yet.

Simple case: After installing app on first ever launch user wanted to change language. And here is the result in logs.

```
D/Phrase OTA: Reading cached Translation failed: /data/user/0/com.example.android/files/.phrase_cache/_some_file_id_.xml: open failed: ENOENT (No such file or directory)
D/Phrase OTA: Request URL: https://ota.phraseapp.com/_DISTRIBUTION_ID_/_ENVIRONMENT_ID_/en/xml?client=android&unique_identifier=_some_unique_identifier_&sdk_version=3.2.5&app_version=1.0.0
E/: Phrase initial update succeed
D/Phrase OTA: Reading cached Translation failed: /data/user/0/com.example.android/files/.phrase_cache/_some_file_id_.xml: open failed: ENOENT (No such file or directory)
D/Phrase OTA: Request URL: https://ota.phraseapp.com/_DISTRIBUTION_ID_/_ENVIRONMENT_ID_/en/xml?client=android&unique_identifier=_some_unique_identifier_&sdk_version=3.2.5&app_version=1.0.0
```

What we are suggesting is that it will be better to have an _async_ function which will trigger to download all available translated texts if there is need(**in our case it's important**)

JFYI: We have all embedded strings stored in resources, but it's important to have all updated texts ready from the begging.

Thanks in advance!

**Comment by theSoenke** [comment]
Hi @ma-unicsoft, the SDK is a built around the concept of only fetching one language at a time to minimize the amount of data transferred. But if you would like to know when an update has been complete for a language you could use the callback:

```
Phrase.updateTranslations(new TranslationsSyncCallback() {
    @Override
    public void onSuccess(boolean translationsChanged) {
    }

    @Override
    public void onFailure() {
    }
});
```

Does this maybe already help in your case?

**Comment by theSoenke** [comment]
Hi @ma-unicsoft, I will close the issue for now as we currently do not plan to support this. Fetching all languages at once can cause a lot of traffic and in most cases users will rarely see all locales, why we think it would cause a lot of overhead to fetch all locales.
