### ISSUE TITLE
Phrase compose SDK download fails with 401 unauthorized

### ISSUE THREAD

**Issue by nmrsmn** [phrase/phrase-android#58]
I've added the compose dependency to my gradle files and for both version 3.3.0 and 3.3.1 I'm getting a 401 unauthorized response when syncing my project. Can you fix this?

**Comment by theSoenke** [comment]
Hi @nmrsmn, thanks for reporting it. I'm looking into this to fix the issue

**Comment by theSoenke** [comment]
Hi @nmrsmn, could you try it with this package: `com.github.phrase:android-sdk:android-sdk-compose:3.3.1`?

**Comment by phuongdat-tran** [comment]
Hi ! 👋  I have the same issue : 

> Could not GET 'https://europe-west1-maven.pkg.dev/mobile-platform-dey5/mobile-platform-repo/com/github/phrase/android-sdk/android-sdk-compose/3.3.2/android-sdk-compose-3.3.2.pom'. Received status code 401 from server: Unauthorized

I tried with version 3.3.0, 3.3.1 and 3.3.2.

Do you have an idea?

Thank you

**Comment by phuongdat-tran** [comment]
I had to add my company SSL certificate for it works !
