### ISSUE TITLE
Add `convert_placeholder` and `enclose_in_cdata` support for the SDK 

### ISSUE THREAD

**Issue by mozarty** [phrase/phrase-android#6]
our project uses iOS placeholders by default and we use `convert_placeholder` in our android yml file 

which causes the SDK to crash when it retrieves the strings 

same for `enclose_in_cdata`

**Comment by theSoenke** [comment]
Hi @mozarty, this is an issue we also have on our roadmap. I will keep you updated as soon as it is solved

**Comment by ponsuyambu** [comment]
@theSoenke Even we have the same issue, any update when it ll be solved?

**Comment by theSoenke** [comment]
Hi @ponsuyambu, thanks for letting us know. I can't promise an exact date yet but this has a high priority for us and I hope that I will be able to provide an update in the next few days

**Comment by theSoenke** [comment]
@mozarty We have added this to our roadmap and will likely start tackling this next week

**Comment by mozarty** [comment]
Thanks for the update , Hope we can use the OTA SDK soon

**Comment by mozarty** [comment]
@theSoenke can the SDK be open-source ? 
i will be more than happy to contribute to make sure this is fixed

**Comment by manuelgon47** [comment]
@theSoenke 
We are also looking forward to this feature, any update or estimated delivery date?

**Comment by theSoenke** [comment]
Hi @mozarty, at this point we have no specific plan to make the SDK open source. But we might consider it in the future. In this case it would only help so much because most changes are server-side.

We are working on this feature right now and I hope that we will be able to provide a solution in the next couple of days

**Comment by mozarty** [comment]
Any updated or a soon release date?

**Comment by mozarty** [comment]
😔

**Comment by mozarty** [comment]
@theSoenke should we give up ?

**Comment by docstun** [comment]
@mozarty sorry for the delay here. We have started working on a solution but we're not at 100% yet. We are targeting a release for this until the end of the year but I cannot give you a specific date at this point.

**Comment by theSoenke** [comment]
Version 2.0 has now been released which includes automatic conversion of iOS placeholders and CDATA support. The enclose in CDATA option can be enabled in the distribution settings on Phrase. To make sure that CDATA escaped translations are served to the app it is required to create a new release after the option has been enabled.

https://github.com/phrase/phrase-android/releases/tag/2.0.0

Let me know if there are still any questions about this
