### ISSUE TITLE
Protect language files served by Phrase OTA

### ISSUE THREAD

**Issue by elad-nanit** [phrase/phrase-android#61]
https://cdn.phraseapp.com/ota/12345/67890/xml/he-IL.xml
(I replaced the real IDs in the URL)

Can this file be protected in some way? for example by using a token in the URL or in the request header.
We would like to make our content not accessible from outside the app.
Currently, anyone with this link can access the file and view its content.
Thanks

**Comment by theSoenke** [comment]
Hi @elad-nanit, the access the translation both the distribution and environment token need to be known. If a person is able to get the full URL the person will quite likely be able get the value for the request header as well. For this it it would be necessary to extract the id and token from the app. Similarly without OTA it's possible to extract the translations strings.xml files from the app itself. But we are still considering adding using a header in the next iteration of the API.
