### ISSUE TITLE
Do I always need to restart the app in order to see the updated changes?

### ISSUE THREAD

**Issue by shahwaiz90** [phrase/phrase-android#63]
Do I always need to kill the app and open again, in order to see the updated changes? Even if I use 
`Phrase.updateTranslations()` in BaseActivity or BaseFragment, The Url is called but changes only reflect when app is restarted.

In BaseActivity Im using following code
 ` override fun getDelegate(): AppCompatDelegate {
        return Phrase.getDelegate(this, super.getDelegate())
    }
override fun attachBaseContext(newBase: Context) {
        Phrase.wrapContext(newBase)
}`

In  MyApplication class : Application 
`
         
           Phrase.setup(this, "distribution", "environment")
            Phrase.updateTranslations()
            Phrase.setTimeout(10000)
            Phrase.updateTranslations(object : TranslationsSyncCallback {
                override fun onSuccess(translationsChanged: Boolean) {
                    Timber.e("Request URL: Phrase New Translation Success: $translationsChanged")
                }
                override fun onFailure() {
                    Timber.e("Request URL: Phrase Failure")
                }
            })
}`

**Comment by theSoenke** [comment]
Hi @shahwaiz90, currently the behaviour is as described by you that the app needs to be restarted to display the latest fetched translations. We are currently looking into extending SDK to provide a way to immediately display the latest translations after an update. I will let you know here when there is an update regarding this.

**Comment by PierreMardon** [comment]
I was looking exactly for this for both iOS and Android.
Big +1 for this enhancement!

**Comment by theSoenke** [comment]
Hi @shahwaiz90 @PierreMardon, with the latest Android release it's now possible to apply updates directly once they're available: https://github.com/phrase/phrase-android/releases/tag/3.8.0 For iOS this is unfortunately harder as translations bundled are cached during the start and cannot be changed later

**Comment by PierreMardon** [comment]
Just to testify about a business use case: we have some entities that are provided by our backend, and a client app update adoption time of ~6 months (after which we can force the users to update).

Relying on OTA to provide new entities related translations would work nicely with Android new behavior, but for iOS it means that we have to ignore new entities until the translations are available, and the time before their availability depends on app user or os killing then relaunching the app. It implies that if these new entities are time critical and cannot be ignored until next app launch, we have to implement a specific backend translations mechanism 😢 which we do.

Is it planned for iOS to manage translations live update at some point? 🙏

**Comment by theSoenke** [comment]
Hey @PierreMardon, thanks for describing your use case! There are definitely a few more technical hurdles on iOS but we're currently investigating a possible approach. I'll let you know when there is an update
