### ISSUE TITLE
Version 3.7.1 is still not available on the maven repository

### ISSUE THREAD

**Issue by gouvinb** [phrase/phrase-android#64]
Hi,

I don't want to appear impatient and if you find this post inappropriate, I apologize.

I don't know if this is normal, but I can implement 3.6.2 and 3.7.0, but not the latest version.

Version 3.7.1 is still not available on the maven repository.

**Comment by theSoenke** [comment]
Hi @gouvinb, thanks a lot for pointing it out. There was actually an issue that prevented the release from being published to Maven. This has now been resolved with the latest release 3.7.1 being accessible from the Maven.
