### ISSUE TITLE
Recent releases all have the same hash

### ISSUE THREAD

**Issue by wandersiemers** [phrase/phrase-android#66]
Hi Phrase team,

I noticed all recent releases have the same hash and seemingly the same zip of the code. This was surprising to me when downloading the code from a release and finding it's all from February 3.

Image from the Releases page:

![Screenshot 2023-10-24 at 13 41 13](https://github.com/phrase/phrase-android/assets/5548333/ec22ff5c-7d6d-4685-95b4-399a3f7ab632)

**Comment by theSoenke** [comment]
Hi @wandersiemers, this repo is used to list releases with a changelog and track issues. It does not contain the source code itself. The aar releases files itself are all different. Hope that helps :)
