### ISSUE TITLE
Theme not changed in runtime when Phrase initialized with custom locale

### ISSUE THREAD

**Issue by igor-alyoshin** [phrase/phrase-android#68]
I try to set default locale when application starts.

I called in application class 
1. Phrase.setup(context, id, secret) + updateTranslations(callback)
2. override attachBaseContext
3. also in attachBaseContext I call setLocaleCode(customLocale)+updateTranslations()
Eventually when first launch app activity has incorrect locale

I try to call in application
Phrase.setup(context, id, secret, customLocale) - default locale fixed, **but** application theme (dark or light) can't change in runtime

If I call setLocaleCode(customLocale)+updateTranslations() in activity - same result as above

It looks like a bug. Is any workaround in this case?

**Comment by theSoenke** [comment]
Hi @igor-alyoshin, I'm not aware of an issue with switching themes and custom locales yet. We will try to take a look to reproduce this

**Comment by hahmed-dev** [comment]
Hi @igor-alyoshin could you please share the version of the SDK you are using?

**Comment by theSoenke** [comment]
Hi @igor-alyoshin, we have released a new version 3.10.0 which should solve this issue: https://github.com/phrase/phrase-android/releases/tag/3.10.0 Please let us know if you still run into any issues
