### ISSUE TITLE
jitpack build failed 

### ISSUE THREAD

**Issue by frckm** [phrase/phrase-android#69]
Hi there - I wanted to update my sdk version because of a crash and saw that the build seem to be failing: 
https://jitpack.io/#phrase/android-sdk

**Comment by jablan** [comment]
@frckm could you pls try using our repository directly, instead of jitpack:

https://support.phrase.com/hc/en-us/articles/5804059067804-Over-the-Air-Strings-#include-the-sdk-0-7

**Comment by frckm** [comment]
@jablan using it directly works - Is there a reason we can't use the sdk via jitpack anymore? Is that a temporary issue?

**Comment by jablan** [comment]
we've had lots of problems with jitpack in the past (mostly regarding reliability), so we started publishing to our local repository. we haven't looked more deeply into the current issue on jitpack you are seeing, we might do that if we find some time.

**Comment by frckm** [comment]
Alright! Thanks for the info
