### ISSUE TITLE
In new versions of SDK translation doesn't always refresh

### ISSUE THREAD

**Issue by AndroidDeveloperEob** [phrase/phrase-android#71]
Previous version of SDK:
3.1.6 <- with workaround on webView
tested  SDK versions:
3.2.0-3.2.4, 3.3.0, 3.5.0, 3.8.0

On each SDK we have an issue related to refreshing  translations after 4-5 changing translations. 
Issue is: not translated strings to selected language

What we trigger when user is changing language:

```
private fun changeAppLanguage(storeLocale: java.util.Locale) {
    val localeCode = storeLocale.toString()
    if (Phrase.getLocaleCode() != localeCode) {
        Phrase.setLocaleCode(localeCode)
        java.util.Locale.setDefault(storeLocale)
        TranslationFactory.forceTranslation(Locale.withLanguageCode(storeLocale.language))
    }
```
This code is always triggered, only after 4-5 triggers Phrase does not change language in app.
Phrase uses in app:
```
open class BaseActivity : AppCompatActivity() {

    override fun getDelegate(): AppCompatDelegate =
        Phrase.getDelegate(this, super.getDelegate())
}
```

```
APP : Application(){

    private fun initPhrase(storeLocale: String) {
        Phrase.setup(
            this,
            PHRASE_DISTRIBUTION_ID,
            PHRASE_SECRET,
            storeLocale
        )
        appInfoProvider.getCoreSemanticAppVersion()?.let {
            Phrase.setAppVersion(it)
        } ?: ExceptionReporter.logException(
            IllegalStateException("Invalid app version. Cannot get core semantic app version")
        )
        Phrase.updateTranslations()
    }
    
      override fun attachBaseContext(base: Context) =
        super.attachBaseContext(Phrase.wrapContext(base))

}
```

Do you have any workaround/solution for the issue?
What kind of additional data could I prepare for you?

**Comment by theSoenke** [comment]
Hi @AndroidDeveloperEob, do I understand it correctly that the translations are not updated for you after switching the language? Could you try the latest release 3.9.0? It contains a fix for using the bundled translations correctly as fallback when locales are switched and over-the-air translations are not present yet

**Comment by AndroidDeveloperEob** [comment]
Hi, yes. We had issue related to translation to version 3.8.0. In 3.9.0 we cannot reproduce the issue. Thanks

**Comment by theSoenke** [comment]
Glad to hear that!
