### ISSUE TITLE
App using Phrase OTA doesn't pick up changed locale without cold start

### ISSUE THREAD

**Issue by bjoernQ** [phrase/phrase-android#9]
How to reproduce:
- have an app with Phrase OTA
- launch the app
- leave app via home button
- go to system settings and change the system locale
- go back to the app with Phrase OTA via recent applications
- the app didn't pick up the changed locale

When force closing the app / swiping the app from the recent apps and relaunching the app the changed system locale is picked up

**Comment by theSoenke** [comment]
Hi @bjoernQ, right now the locale is being setup once when `PhraseApp.setup()` is called. Changing the locale while is the app is still open has no effect right now. One workaround right now would be to call `PhraseApp.setup()` again after the locale has been changed.

It seems useful to do this automatically and I will have a look whether we can include it in one of the next releases

**Comment by theSoenke** [comment]
Version 2.1.0 was just released which now detects system locale changes and fetches the most recent translations for the new locale and picks up the system locale
